### ISSUE TITLE
How to modify the resoution of the image captured from the camera?

### ISSUE THREAD

**Issue by zhongwenkun886** [nihui/ncnn-android-nanodet#10]
In your project, the resoution of the imge captured from the camera is a little low. I want get higher  resoution ，so how to modify the code? 
Thanks!

**Comment by nihui** [comment]
https://github.com/nihui/ncnn-android-nanodet/blob/acb9dd3cbeb3b5e090c6baea73bba501b66cd2de/app/src/main/jni/ndkcamera.cpp#L183
