### ISSUE TITLE
how to make a button click that get the camera image and bounding box coordinates

### ISSUE THREAD

**Issue by nqthai309** [nihui/ncnn-android-nanodet#17]
how to make a button click that get the camera image and bounding box coordinates. I want to build an app based on it

**Comment by cyrillkuettel** [comment]
Hi @nqthai309 
I'm a little late, I created something that you might find interesting. I created a callback to java with information about the current object (including bounding box coordinates). 
https://github.com/cyrillkuettel/ncnn-android-nanodet/tree/28dc670a3b0c03c195af102666a52bcb1d92f65d
I hope this is useful to you.

It basically works like this:
```cpp
void MyNdkCamera::on_image_render(cv::Mat& rgb) const
{
    // nanodet
    {
        ncnn::MutexLockGuard g(lock);

        if (g_nanodet)
        {
            std::vector<Object> objects;
            g_nanodet->detect(rgb, objects);
            g_nanodet->draw(rgb, objects);

            for (auto &object : objects) {
                const char *label = class_names[object.label];
                const float prob = object.prob;
                const cv::Rect_<float> rectangle = object.rect;
                // calls a method in MainActivity
               call_java_method(label, prob, rectangle);
            }
        }
```
Then, in the MainActivity, you receive the label, probabiility and coordinates and can do whatever you want with it.
